### ISSUE TITLE
Hex Values not working in SCSS files (sublime text 4)

### ISSUE THREAD

**Issue by codingcarpenter** [jwortmann/quick-view#2] opened 2021-05-23 20:48 UTC
I'm using ST4 and I've noticed while named values work for previews, hex values only reveal a grey box.
![example](https://user-images.githubusercontent.com/2285699/119276054-7759dd80-bbcd-11eb-9532-812d70954cdf.png)

Testing in a standard css file works as expected.

**Comment by jwortmann** [comment] 2021-05-23 21:19
Thanks for the report! Looks like I've missed this case when I tested various syntaxes. This seems to be caused by a weird/wrong choice of scope names in the syntax of the "SCSS" package, but I will fix it and make a new release soon (probably in a few days).

As a workaround for now, I could suggest to use the syntax from the [Sass](https://packagecontrol.io/packages/Sass) package from Package Control instead, despite its name it also comes with a SCSS syntax and it seems to be much more maintained than the "SCSS" package (Sass package last updated yesterday, SCSS package last updated 7 years ago). I don't know whether there are any other features only present in one of the packages though.

**Comment by codingcarpenter** [comment] 2021-05-23 21:29
Oh I didn't even realize the disparity in updates. Thanks for the heads up. I'm going to switch packages based on this new information.

Thanks a ton! Any chance this is ever going to expand to Sass variables?

**Comment by jwortmann** [comment] 2021-05-23 22:33
> Any chance this is ever going to expand to Sass variables?

Yes, I'd like to see if I can tweak the popup appearance for ST4 a bit next, and after that I will try to add support for Sass, SCSS and Less variables too. I can't promise too much and it will depend a bit on the corresponding syntax packages how well I can support them, but I think I will get it to work for most of the cases.

**Comment by jwortmann** [comment] 2021-05-27 15:19
This issue should be fixed now and I have enabled the color previews for variables in .sass, .scss and .less files (with the syntaxes from the Sass and LESS packages). This probably works only for simple cases (i.e. there must be exactly 1 definition for the variable in the same file) and for variables with standard CSS color syntax.

If there are still issues for things that you expect to work, I'd be happy to hear feedback, because I personally haven't used these CSS preprocessor languages myself yet.

I've made a new release for this package now, but it will take a few hours for Package Control to see the update.

**Closed as completed by jwortmann** 2021-05-27 15:19 UTC
